version: "3"
services:
  tflCamApp:
    container_name: tflcamapp
    image: f4zphp27xi2s27yn/my_repo_topor:tflcamapp
    ports:
      - 4000:80
  tflCamAppApi:
    container_name: tflcamappapi
    image: f4zphp27xi2s27yn/my_repo_topor:tflcamsmapsapi
    environment:
      - MONGOOSE_CONNECTION_STRING
      - MONGOOSE_USER
      - MONGOOSE_PASS
    ports:
      - 3200:3200
networks:
  default:
    external: true
    name: myNetwork
